ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER geodata IDENTIFIED BY "Passw0rd!" DEFAULT TABLESPACE users QUOTA UNLIMITED ON users TEMPORARY TABLESPACE temp;
GRANT CREATE SESSION TO geodata;
GRANT ALL PRIVILEGES TO geodata;

exit