CREATE LOGIN StackExchange WITH PASSWORD = 'Passw0rd!', CHECK_POLICY = OFF;
CREATE DATABASE StackExchange;
ALTER AUTHORIZATION ON DATABASE::StackExchange TO StackExchange;
GO

USE StackExchange;
GO

CREATE TABLE Badges (Id INT NOT NULL, Name NVARCHAR(40) NULL, UserId INT NOT NULL, CreationDate DATETIME NOT NULL, CONSTRAINT Badges_PK PRIMARY KEY (Id));
CREATE TABLE Comments (Id INT NOT NULL, CreationDate DATETIME NOT NULL, PostId INT NOT NULL, Score INT NULL, Text NVARCHAR(700) NULL, UserId INT NULL, CONSTRAINT Comments_PK PRIMARY KEY (Id));
CREATE TABLE LinkTypes (Id INT NOT NULL, Type NVARCHAR(50) NULL, CONSTRAINT LinkTypes_PK PRIMARY KEY (Id));
CREATE TABLE PostLinks (Id INT NOT NULL, CreationDate DATETIME NOT NULL, PostId INT NOT NULL, RelatedPostId INT NOT NULL, LinkTypeId INT NOT NULL, CONSTRAINT PostLinks_PK PRIMARY KEY (Id));
CREATE TABLE Posts (Id INT NOT NULL, AcceptedAnswerId INT NULL, AnswerCount INT NULL, Body VARCHAR(MAX) NOT NULL, ClosedDate DATETIME NULL, CommentCount INT NULL, CommunityOwnedDate DATETIME NULL, CreationDate DATETIME NOT NULL, FavoriteCount INT NULL, LastActivityDate DATETIME NOT NULL, LastEditDate DATETIME NULL, LastEditorDisplayName NVARCHAR(40) NULL, LastEditorUserId INT NULL, OwnerUserId INT NULL, ParentId INT NULL, PostTypeId INT NOT NULL, Score INT NOT NULL, Tags NVARCHAR(150) NULL, Title NVARCHAR(250) NULL, ViewCount INT NULL, CONSTRAINT Posts_PK PRIMARY KEY (Id));
CREATE TABLE PostTypes (Id INT NOT NULL, Type NVARCHAR(50) NULL, CONSTRAINT PostTypes_PK PRIMARY KEY (Id));
CREATE TABLE Users (Id INT NOT NULL, AboutMe VARCHAR(MAX) NULL, Age INT NULL, CreationDate DATETIME NOT NULL, DisplayName NVARCHAR(40) NULL, DownVotes INT NOT NULL, EmailHash NVARCHAR(40) NULL, LastAccessDate DATETIME NOT NULL, Location NVARCHAR(100) NULL, Reputation INT NOT NULL, UpVotes INT NOT NULL, Views INT NOT NULL, WebsiteUrl NVARCHAR(200) NULL, AccountId INT NULL, CONSTRAINT Users_PK PRIMARY KEY (Id));
CREATE TABLE Votes (Id INT NOT NULL, PostId INT NOT NULL, UserId INT NULL, BountyAmount INT NULL, VoteTypeId INT NOT NULL, CreationDate DATETIME NOT NULL, CONSTRAINT Votes_PK PRIMARY KEY (Id));
CREATE TABLE VoteTypes (Id INT NOT NULL, Name NVARCHAR(50) NULL, CONSTRAINT VoteTypes_PK PRIMARY KEY (Id));
GO

CREATE TABLE Import_Badges (Id INT NOT NULL, Name NVARCHAR(40) NULL, UserId INT NOT NULL, CreationDate DATETIME NOT NULL);
CREATE TABLE Import_Comments (Id INT NOT NULL, CreationDate DATETIME NOT NULL, PostId INT NOT NULL, Score INT NULL, Text NVARCHAR(700) NULL, UserId INT NULL);
CREATE TABLE Import_LinkTypes (Id INT NOT NULL, Type NVARCHAR(50) NULL);
CREATE TABLE Import_PostLinks (Id INT NOT NULL, CreationDate DATETIME NOT NULL, PostId INT NOT NULL, RelatedPostId INT NOT NULL, LinkTypeId INT NOT NULL);
CREATE TABLE Import_Posts (Id INT NOT NULL, AcceptedAnswerId INT NULL, AnswerCount INT NULL, Body VARCHAR(MAX) NOT NULL, ClosedDate DATETIME NULL, CommentCount INT NULL, CommunityOwnedDate DATETIME NULL, CreationDate DATETIME NOT NULL, FavoriteCount INT NULL, LastActivityDate DATETIME NOT NULL, LastEditDate DATETIME NULL, LastEditorDisplayName NVARCHAR(40) NULL, LastEditorUserId INT NULL, OwnerUserId INT NULL, ParentId INT NULL, PostTypeId INT NOT NULL, Score INT NOT NULL, Tags NVARCHAR(150) NULL, Title NVARCHAR(250) NULL, ViewCount INT NULL);
CREATE TABLE Import_PostTypes (Id INT NOT NULL, Type NVARCHAR(50) NULL);
CREATE TABLE Import_Users (Id INT NOT NULL, AboutMe VARCHAR(MAX) NULL, Age INT NULL, CreationDate DATETIME NOT NULL, DisplayName NVARCHAR(40) NULL, DownVotes INT NOT NULL, EmailHash NVARCHAR(40) NULL, LastAccessDate DATETIME NOT NULL, Location NVARCHAR(100) NULL, Reputation INT NOT NULL, UpVotes INT NOT NULL, Views INT NOT NULL, WebsiteUrl NVARCHAR(200) NULL, AccountId INT NULL);
CREATE TABLE Import_Votes (Id INT NOT NULL, PostId INT NOT NULL, UserId INT NULL, BountyAmount INT NULL, VoteTypeId INT NOT NULL, CreationDate DATETIME NOT NULL);
CREATE TABLE Import_VoteTypes (Id INT NOT NULL, Name NVARCHAR(50) NULL);
GO
